// Mocks generated by Mockito 5.4.6 from annotations
// in tic_tac_toe/test/mock_factory.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tic_tac_toe/data/models/player.dart' as _i4;
import 'package:tic_tac_toe/data/models/tile_state.dart' as _i3;
import 'package:tic_tac_toe/data/repositories/computer_repository.dart' as _i2;
import 'package:tic_tac_toe/data/repositories/stats_repository.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ComputerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockComputerRepository extends _i1.Mock
    implements _i2.ComputerRepository {
  @override
  int chooseMove(List<_i3.TileState>? board, _i4.Player? computerPlayer) =>
      (super.noSuchMethod(
            Invocation.method(#chooseMove, [board, computerPlayer]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);
}

/// A class which mocks [StatsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStatsRepository extends _i1.Mock implements _i5.StatsRepository {
  @override
  _i6.Future<Map<String, dynamic>> loadStats() =>
      (super.noSuchMethod(
            Invocation.method(#loadStats, []),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<void> saveStats(Map<String, dynamic>? stats) =>
      (super.noSuchMethod(
            Invocation.method(#saveStats, [stats]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
